#! /bin/bash
## **** This is a WIP. The tofu has NOT been updated to use the manifest created by this script or deploy redis  ****
### Note: The manifest that is generated by this script contains sensitive
###       information. If you commit it to a git repo, make sure it is private.

# Templates the dandydev/redis-ha helm chart using the 'redis-ha-values.yaml' values file in this 
# directory, saving the output values to an env/manifests/redis-ha-values.yaml.
# If you plan on installing Redis HA, make sure to set 'talos_cluster.redis_ha_enabled=true' 
# in your .env/{your_environment}.tfvars file after templating the charts.
set -e

minify='false'
for arg in "$@"; do
  if [[ "${arg,,}" == "minify" ]]; then
    minify='true'
  fi
done

NAMESPACE='cluster-redis'
NAMESPACE_MANIFEST=$(
cat <<EOM
apiVersion: v1
kind: Namespace
metadata:
  name: $NAMESPACE
EOM
)

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
TEMPLATE_VALUES="${SCRIPT_DIR}/values/redis-ha-values.yaml"
OUTPUT_MANIFEST="${SCRIPT_DIR}/../.env/manifests/redis-ha-manifest.yml"

echo "### Adding dandydev Helm Repository ###"
helm repo add dandydev https://dandydeveloper.github.io/charts
helm repo update

echo "### Creating Redis HA Manifest ###"
redis_password=$(openssl rand 16 | base64 -w 0)

# echo helm install redis-ha dandydev/redis-ha --version 4.35.2 --namespace $NAMESPACE --create-namespace -f "${TEMPLATE_VALUES}" --set-string redisPassword="${redis_password}"
# exit
# helm install redis-ha dandydev/redis-ha --version 4.35.2 \
#     --namespace $NAMESPACE --create-namespace \
#     -f "${TEMPLATE_VALUES}" \
#     --set-string redisPassword="${redis_password}"
# exit
manifest="$(helm template redis-ha dandydev/redis-ha --version 4.35.2 \
    --namespace $NAMESPACE --create-namespace \
    -f "${TEMPLATE_VALUES}" \
    --set-string redisPassword="${redis_password}" \
    --dry-run=server --validate)"
# Prepend namespace
manifest="${NAMESPACE_MANIFEST}"$'\n'"${manifest}"

if [[ "$minify" == 'true' ]]; then
    echo " **Minifying output manifest with yq**"
    yq '... comments=""' <<< "$manifest" > "$OUTPUT_MANIFEST" 
else
    echo "$manifest" > "$OUTPUT_MANIFEST" 
fi

echo ""
echo "### Templating Complete ###"
echo "Manifest file saved to: $(realpath "${OUTPUT_MANIFEST}")."
echo "Make sure to enable the 'talos_cluster.redis_ha_enabled' setting in your tfvars file to enable the installation of a Redis HA Cluster."